### ISSUE TITLE
Several domains, same operator?

### ISSUE THREAD

**Issue by acrogenesis** [adyanth/cloudflare-operator#60]
I'm deploying this in an environment where different domain names (not subdomain) need to be used.
Should I create separate `clustertunnel.yaml`s?

**Comment by adyanth** [comment]
Ideally, I do not see anything stopping you from using multiple domains on the same tunnel. I have not tried this out (I only have one domain managed by Cloudflare), but it should work. The ClusterTunnel.spec.cloudflare.domain is only used for pushing DNS entries, and that will not work for any other domains you will add. But the tunnel itself "should" work.

Other than that, yes, creating a new clustertunnel resource would work as you expect and will be able to manage one domain mapped to one tunnel.

**Comment by acrogenesis** [comment]
Thanks @adyanth using the same tunnel and the fqdn annotation didn't work. Although a new clustertunnel.yaml configuration worked great.

How many subdomains would you think are a limit per tunnel? Or kb/s ?

**Comment by adyanth** [comment]
I'll try that out sometime, since I don't see a reason why the tunnel shouldn't work.

Regarding the performance of cloudflared, the [documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/hosting-requirements/) doesn't state any upper bound, just limited by the performance of the underlying hardware. In my usage, I serve around 20 subdomains with bandwidth exceeding 300Mbps without issues.

**Comment by acrogenesis** [comment]
Awesome, thanks!
