### ISSUE TITLE
Command line arguments for Operator

### ISSUE THREAD

**Issue by acrogenesis** [adyanth/cloudflare-operator#61]
In the docs https://github.com/adyanth/cloudflare-operator/blob/main/docs/configuration.md#operator it says you can add command line arguments like `--overwrite-unmanaged-dns` but it isn't clear to me where or how this should be done.

Thanks

**Comment by adyanth** [comment]
Hey @acrogenesis,
It is to be added to the deployment's spec.template.spec.containers[1].args after --leader-elect. Currently, it is a manual step, but I am planning to worry about making it easier to configure when I start looking into Helm charts for it since there are very few meaningful configurable parameters for now.

Obligatory patch: (Note that it is not idempotent)

```bash
kubectl -n cloudflare-operator-system patch deploy cloudflare-operator-controller-manager --type=json -p='[{"op": "add", "path": "/spec/template/spec/containers/1/args/-", "value": "--overwrite-unmanaged-dns=true"}]'
```

Reference:
https://github.com/adyanth/cloudflare-operator/blob/702e042e33c1cf802c80a0e3aaf73b20e515409e/main.go#L60

**Comment by acrogenesis** [comment]
That makes sense. Thanks!
