### ISSUE TITLE
Customising dns subdomain

### ISSUE THREAD

**Issue by spookyuser** [adyanth/cloudflare-operator#66]
Hi, this is truly an incredible project! So simple to understand and extremely well documented, thank you sm!

It's so far ahead of anything official from cloudflare especially since the first step in their k8s documentation is to ssh into your node and install cloudflared lol.

Quick question: I might be have missed it in the documentation but is there any way to customize the subdomain your  service will appear on once installed? And perhaps have no subdomain at all, if not no worries I could just do a cname in the cloudflare dashboard! 

Thanks!

**Comment by adyanth** [comment]
Hey @spookyuser, thanks so much for the kind words :)

For customizing the subdomain, see [Service Annotations](https://github.com/adyanth/cloudflare-operator/blob/main/docs/configuration.md#service-annotations). Specifically, `cfargotunnel.com/fqdn` sets the public fqdn to whatever you specify. E.g.: `cfargotunnel.com/fqdn: service.mydomain.com`

I have not tested setting the root domain like this, since Cloudflare tunnels work with CNAME to the tunnel domain, and root domains do not support CNAME, only ANAMEs (in Cloudflare DNS. Some DNS providers don't support this at all), and the operator only supports setting CNAMEs. I would recommend to do that yourself for the root domain. Rest can be handled by this operator.

**Comment by spookyuser** [comment]
Wow sorry not sure how I missed that, exactly what I needed, thanks again!
